---
- name: Install iTop
  hosts: argentina.eastus.cloudapp.azure.com
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: remove nginx
    yum:
      name: nginx
      state: absent

  - name: Install packages using yum
    yum:
      name:
        - httpd
        - mysql
        - mysql-server
        - php
        - php-mysql
        - php-mcrypt
        - php-xml
        - php-cli
        - php-soap
        - php-ldap
        - graphviz
      state: present

  - name: Enable services wtih systemctl
    service:
      name:
        - httpd
        - mysqld
      state: enable

  - name:
    service:
      name: httpd
      state: started
