---
- name: Install iTop
  hosts: argentina.eastus.cloudapp.azure.com
  vars:
    post_max_size: 32M
    suhosin_get_max_value_length: 2048
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install the remi and ius repo from remote repo
    yum:
      name:
        - "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
        - "https://centos{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm"

  - name: Enable remi-php71 repository
    shell: yum-config-manager --enable remi-php71


  - name: Install packages using yum
    yum:
      name:
        - httpd
        - mariadb
        - mariadb-server
        - php
        - php-mysql
        - php-mcrypt
        - php-xml
        - php-cli
        - php-soap
        - php-ldap
        - graphviz
      state: present

  - name: Set SELinux for httpd
    seboolean:
      name:
        - httpd_can_network_connect
        - httpd_can_network_connect_db
      state: yes
      persistent: yes

  - name: Enable services wtih systemctl
    service:
      name:
        - httpd
        - mysqld
      state: enable

  - name: Custom /etc/php.ini
    template:
      src: php.ini.j2
      dest: /etc/php.ini

  - name: Starting service Apache
    service:
      name: httpd
      enabled: yes
      state: started

  - name: Starting service MySQL/mariaDB
    service:
      name: mariadb
      enabled: yes
      state: started
